HasCJKLanguage = true
baseurl = "https://catatsu.github.io"
title = "Catatsu Tech Blog"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Benoît Benedetti"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "CatatsuはHASIGOです"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "github"
  url = "https://github.com/Catatsu"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

[permalinks]
    post = "/:year/:month/:day/:slug"
